### PR TITLE
STY,MAINT: Style of coding enhanced

### PR DESCRIPTION
**Pull request by surevs**
Following are the specific and detail changes which are implemented as a part of this pull request:
- possible PEP8 fixes have been done which does not affect the functionality of code
- Futures have been added to requirements to ensure things work correct as expected as python 2.7 core does not include it at `requirements.txt:11`
- Good to have grpc as part of requirements - `requirements.txt:12`
- Imported specific `ThreadPoolExecutor` as it is only used in `start.py`
- Updated the try import of collections to reflect based on python version at `getgauge\python.py:6`

### CODE REVIEW

**Comment by surevs** [comment]
@gaugebot CLA is already signed

**Comment by sriv** [comment]
@gaugebot recheck

**Comment by sriv** [comment]
@surevs - looks like the bot is misbehaving, we'll get that sorted in a bit. Sorry about that.

**Comment by surevs** [comment]
Thanks a lot @sriv , Will await for your review comments.

**Comment by surevs** [comment]
- `grpc` has been removed from the requirements as `grpcio` and `grpcio-tools` already exists

**Comment by surevs** [comment]
@gaugebot recheck

**Comment by surevs** [comment]
@sriv please advise in case of any changes to be done .

**Comment by surevs** [comment]
@gaugebot recheck

**Comment by BugDiver** [comment]
@surevs  Sorry for the delay. Looks like BOT had some issues validating your PR.
I checked the records manually but did not find you.
Can you please sign the CLA at https://gauge-bot.herokuapp.com/cla/
You can validate your self by browsing at https://gauge-bot.herokuapp.com/contributor?checkContributor=YOUR_USER_NAME

**Comment by surevs** [comment]
@gaugebot recheck the pull request.

**Comment by surevs** [comment]
thank you @BugDiver !

**Pull request merged**
