### PR TITLE
Use debugpy instead of ptvsd

### LINKED ISSUE #180: [Feature Request] Update ptvsd to debugpy
Hi! 

I'm a PM working on https://github.com/Microsoft/vscode-python, and I recently learned about the Gauge extension and that it uses ptvsd to debug specifications (which is really cool btw 😊). 

I'm opening this issue because mid next month we'll update ptvsd to debugpy in the Python extension, and we're planning to support ptvsd only until May 1st. Since this could break debugging in the Gauge extension for Python users, I'm opening this request now as a heads up 😊.

Thanks!

### PR DESCRIPTION
**Pull request by NivedhaSenthil**
- since vscode removes support for ptvsd soon

Fixes #180

### CODE REVIEW

**Comment by negiDharmendra** [comment]
Unable to debug Gauge-python specs after installing from [this branch](https://github.com/getgauge/gauge-python/tree/%23180_use_debugpy). 

Screenshot 2020-03-30 at 1 45 16 PM

**Comment by NivedhaSenthil** [comment]
can you please provide steps to replicate ? 
Works fine for me with the below steps

```
gauge uninstall python
pip uninstall getgauge
pip install -r requirements.txt
python build.py --install
```

**Comment by NivedhaSenthil** [comment]
Was there any error logs ?

**Comment by negiDharmendra** [comment]
For some reason vscode is sending the `attach request` first and then `initialize request` which seems to be reason for the issue and explains the error `Session is not initialized yet`
I have raised an issue with [vscode-python](https://github.com/microsoft/vscode-python/issues/10999)

**Pull request merged**
