### PR TITLE
Static loader improvements

### PR DESCRIPTION
**Pull request by surajbarkale**
This PR is result of python3 f-string related failures in my test code. I realised that RedBaron was unable to parse python3 code. I rounded up following fixes into one PR for you:

 - Added exact parsing failure error message. It should help identify unsupported python3 syntax.
 - Used `to_python()` to load step arguments. This is better than using regular expressions to parse already parsed text. 
 - Used `os.walk()` instead of recursive function calls. 
 - Proper span objects are created when a step is loaded. I was not sure why this was done in the `StepInfo` class.
 - Removed usage of inspect which requires source code loading at runtime. The text returned by inspect was not being used anyway.

### CODE REVIEW

**Comment by BugDiver** [comment]
@surajbarkale  Thanks for creating this PR, But I'm still not sure if it fixes the redbaron's python3 issue.
the method which throws the exception is `ast.find_all` which is still used [here](https://github.com/getgauge/gauge-python/pull/95/files#diff-463f6bf5b2322d7b2e37ba65a34bcd26R26) in your PR.

>  I was not sure why this was done in the StepInfo class.

This was done to make the step positions lazy load. The reason is loading the steps with position (redbaron's bounding_box is calculated lazily) takes time which causes performance issue in execution.
For more info refer https://github.com/getgauge/gauge-python/pull/82#issuecomment-391675050, https://github.com/getgauge/gauge-python/issues/54 and https://github.com/getgauge/gauge-python/issues/79

**Comment by surajbarkale** [comment]
@BugDiver I have reverted back to lazy loading the span. This PR is not meant to fix RedBaron issues with Python 3. But to make it easy to find out why a step is not being loaded from valid python code.

We have to move to something like [jedi](https://jedi.readthedocs.io/en/latest/), [astor](https://github.com/berkerpeksag/astor) or [astroid](https://github.com/PyCQA/astroid).

**Comment by BugDiver** [comment]
@surajbarkale Ohk, Got it.

> I can prototype one of these libraries if you are interested. Refactoring is the real challenge here rather than analysis.

Sure, We will really appreciate it. You can reach out to us on our [gitter channel](https://gitter.im/getgauge/chat) for any kind of help. I will be more than happy to help you on this.

I will merge this PR once the build status is green.

**Comment by surajbarkale** [comment]
Sorry I was hasty! I was able to remove `find_all` afterall! Drawback is only top level functions will be detected

**Comment by BugDiver** [comment]
@surajbarkale  I"m closing this PR since your another PR #98  already contains these changes.

**Pull request closed without merging**
